


name: Python movie resource collector from www.dbzyz.com


apis:
  - name: dbzyz
    url: 'http://www.dbzyz.com/inc/dbm3u8.php?ac=videolist&pg={pg}'

database:
  name: mysql
  user: "root"
  passwd: "123456"
  url: "localhost"
  port: "3306"
  db: "collectMovies"

# zdbyz mac type to local type mapper
dbzyz:
  mactype:
     1: 1
     2: 2
     3: 3
     4: 4
     5: 101
     6: 102
     7: 103
     8: 104
     9: 105
     10: 106
     11: 107
     12: 201
     13: 202
     14: 202
     15: 204
     16: 203
     17: 203
     18: 205
     19: 108
     20: 5
     21: 5
     22: 206
     24: 108
  exclude:
     - 108


log:
  pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  file: movies.log


